version: '4.8'
services:
  pokemon-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POKEMON_USER}
      POSTGRES_PASSWORD: ${POKEMON_PASSWORD}
      POSTGRES_DB: ${POKEMON_DB}
    ports:
      - "5432:5432"
    volumes:
      - pokemon_data:/var/lib/postgresql/data

  pokemon-api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    ports:
      - "8000:8020"
    volumes:
      - .:/app

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: pepa-linha-dark
volumes:
  pokemon_data:
    external: true

